### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/INDEX.LIST'

### ISSUE THREAD

**Issue by johnandersen777** [Warchant/iroha-pure-java#58]
When I include this in my `build.gradle` with

```
implementation 'com.github.warchant:iroha-pure-java:v1.0.0_rc2-SNAPSHOT'
```

I get this error on build

```
Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'META-INF/INDEX.LIST'
```

**Comment by johnandersen777** [comment]
I found the solution, just wanted to add it here so anyone else who runs into it can see too.

```
packagingOptions {
    exclude 'META-INF/INDEX.LIST'
    exclude 'META-INF/io.netty.versions.properties'
}
```

**Comment by Warchant** [comment]
@pdxjohnny do you have netty included in your dependencies?

**Comment by johnandersen777** [comment]
Yes, via flutter, my guess is anything that is in both is causing this issue. Weird, must be something wacky with Java or Android build system.

https://github.com/Warchant/iroha-pure-java/blob/e356a116b7ce85244d5d8d9c222f96a2490c748f/proto.gradle#L18-L19
