### ISSUE TITLE
gRPC plaintext connection used

### ISSUE THREAD

**Issue by johnandersen777** [Warchant/iroha-pure-java#60]
As you know I'm new here, but I thought it would be good to have some conversation in the issues so others know the answer as well.

- I know Iroha is signing transactions from clients before sending them out, but are they encrypted as well?
- If not, shouldn't this be an encrypted connection?

https://github.com/Warchant/iroha-pure-java/blob/e356a116b7ce85244d5d8d9c222f96a2490c748f/src/main/java/jp/co/soramitsu/iroha/java/IrohaAPI.java#L46

**Comment by Warchant** [comment]
Transactions are not encrypted.

Privacy is not a goal for current version. In production environment there will be a TLS.

**Comment by johnandersen777** [comment]
Understood, thank you.

Leaving these here for future reference:
- https://github.com/grpc/grpc-java/blob/master/SECURITY.md#transport-security-tls
- https://github.com/grpc/grpc-java/blob/master/examples/example-tls/src/main/java/io/grpc/examples/helloworldtls/HelloWorldClientTls.java

**Comment by Warchant** [comment]
Closing for now
